package dev.vulnalert.service;
import com.fasterxml.jackson.databind.*; import dev.vulnalert.domain.*; import dev.vulnalert.repo.VulnerabilityRepository; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.client.RestClient; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;
@Service
public class NvdIngestionService {
 private final RestClient client; private final VulnerabilityRepository repository; private final MatchingService matching; private final String apiKey;
 public NvdIngestionService(RestClient.Builder builder,VulnerabilityRepository repository,MatchingService matching,@Value("${app.nvd.base-url}")String url,@Value("${app.nvd.api-key:}")String apiKey){client=builder.baseUrl(url).build();this.repository=repository;this.matching=matching;this.apiKey=apiKey;}
 @Scheduled(fixedDelayString="${app.nvd.poll-rate-ms}",initialDelayString="${app.nvd.initial-delay-ms}") public void scheduled(){ingest(Duration.ofHours(8));}
 @Transactional public Map<String,Integer> ingest(Duration window){Instant end=Instant.now(),start=end.minus(window);String format="yyyy-MM-dd'T'HH:mm:ss.SSSXXX";var request=client.get().uri(u->u.queryParam("pubStartDate",DateTimeFormatter.ofPattern(format).withZone(ZoneOffset.UTC).format(start)).queryParam("pubEndDate",DateTimeFormatter.ofPattern(format).withZone(ZoneOffset.UTC).format(end)).queryParam("resultsPerPage",2000).build());if(!apiKey.isBlank())request=request.header("apiKey",apiKey);JsonNode root=request.retrieve().body(JsonNode.class);int imported=0,matched=0;if(root!=null)for(JsonNode wrapper:root.path("vulnerabilities")){JsonNode cve=wrapper.path("cve");String id=cve.path("id").asText();if(repository.findByCveId(id).isPresent())continue;String description="No English description";for(JsonNode d:cve.path("descriptions"))if("en".equals(d.path("lang").asText())){description=d.path("value").asText();break;}JsonNode cvss=cve.path("metrics").path("cvssMetricV31").path(0).path("cvssData");if(cvss.isMissingNode())cvss=cve.path("metrics").path("cvssMetricV30").path(0).path("cvssData");String severityText=cvss.path("baseSeverity").asText("UNKNOWN");Severity severity;try{severity=Severity.valueOf(severityText);}catch(Exception e){severity=Severity.UNKNOWN;}var products=new StringBuilder();cve.path("configurations").findValues("criteria").forEach(n->products.append(n.asText()).append(' '));var v=repository.save(new Vulnerability(id,description,severity,cvss.path("baseScore").isNumber()?cvss.path("baseScore").asDouble():null,Instant.parse(cve.path("published").asText()),Instant.parse(cve.path("lastModified").asText()),"https://nvd.nist.gov/vuln/detail/"+id,products.toString()));imported++;matched+=matching.match(v);}return Map.of("imported",imported,"alertsCreated",matched);}
}
