import {useEffect,useState} from 'react'; import {Bell,Box,ChevronRight,Eye,Plus,RefreshCw,Search,Shield,ShieldAlert,Trash2,TriangleAlert} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:8080'; const headers={'Content-Type':'application/json','X-Demo-User':'demo@vulnalert.local'};
type Watch={id:number,vendor:string,product:string,version?:string}; type Vuln={id:number,cveId:string,description:string,severity:string,cvssScore:number,publishedAt:string,sourceUrl:string}; type Alert={id:number,status:string,createdAt:string,vulnerability:Vuln,watchItem:Watch}; type Dashboard={watchedProducts:number,unreadAlerts:number,newCvesThisWeek:number,alerts:Alert[]};
const empty:Dashboard={watchedProducts:0,unreadAlerts:0,newCvesThisWeek:0,alerts:[]};
const navItems=[{name:'Overview',icon:Box},{name:'Watchlist',icon:Eye},{name:'Alerts',icon:Bell}];
export default function App(){const[dash,setDash]=useState(empty),[watches,setWatches]=useState<Watch[]>([]),[tab,setTab]=useState('Overview'),[loading,setLoading]=useState(false),[form,setForm]=useState({vendor:'',product:'',version:''}),[error,setError]=useState('');
 async function load(){try{const[d,w]=await Promise.all([fetch(`${API}/api/dashboard`,{headers}).then(r=>r.json()),fetch(`${API}/api/watchlist`,{headers}).then(r=>r.json())]);setDash(d);setWatches(w)}catch{setError('API unavailable — start the Docker stack to load live data.')}} useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setLoading(true);await fetch(`${API}/api/watchlist`,{method:'POST',headers,body:JSON.stringify(form)});setForm({vendor:'',product:'',version:''});await load();setLoading(false)}
 async function remove(id:number){await fetch(`${API}/api/watchlist/${id}`,{method:'DELETE',headers});await load()}
 return <div className="shell"><aside><div className="logo"><Shield/><b>VULN<span>ALERT</span></b></div><nav>{navItems.map(({name,icon:Icon})=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}><Icon size={18}/>{name}{name==='Alerts'&&dash.unreadAlerts>0?<i>{dash.unreadAlerts}</i>:null}</button>)}</nav><div className="system"><span><i/> SYSTEM OPERATIONAL</span><small>NVD SYNC · AUTOMATED</small></div></aside><main><header><div><small>SECURITY OPERATIONS</small><h1>{tab}</h1></div><div className="search"><Search size={17}/><input placeholder="Search CVEs, products…"/></div><button className="avatar">DA</button></header>
 {tab==='Overview'&&<><section className="intro"><div><small>THREAT MONITOR</small><h2>Your software.<br/><em>Continuously defended.</em></h2><p>VulnAlert watches newly disclosed vulnerabilities and tells you what matters—before it becomes an incident.</p></div><ShieldAlert size={110}/></section><section className="metrics"><Metric icon={<Eye/>} value={dash.watchedProducts} label="WATCHED PRODUCTS"/><Metric icon={<Bell/>} value={dash.unreadAlerts} label="UNREAD ALERTS" hot/><Metric icon={<TriangleAlert/>} value={dash.newCvesThisWeek} label="NEW CVEs · 7 DAYS"/></section><AlertTable alerts={dash.alerts}/></>}
 {tab==='Watchlist'&&<section className="card"><div className="cardHead"><div><small>SUBSCRIPTIONS</small><h2>Technology watchlist</h2></div></div><form onSubmit={add} className="addForm"><input required placeholder="Vendor (e.g. Apache)" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><input required placeholder="Product (e.g. Log4j)" value={form.product} onChange={e=>setForm({...form,product:e.target.value})}/><input placeholder="Version (optional)" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><button disabled={loading}><Plus size={17}/> WATCH</button></form><div className="watchGrid">{watches.map(w=><div className="watch" key={w.id}><div className="productIcon">{w.product.slice(0,2).toUpperCase()}</div><div><b>{w.product}</b><span>{w.vendor} · {w.version||'All versions'}</span></div><button onClick={()=>remove(w.id)}><Trash2 size={16}/></button></div>)}</div></section>}
 {tab==='Alerts'&&<AlertTable alerts={dash.alerts}/>} {error&&<div className="error">{error}</div>}</main></div>}
function Metric({icon,value,label,hot=false}:{icon:React.ReactNode,value:number,label:string,hot?:boolean}){return <div className={'metric '+(hot?'hot':'')}><span>{icon}</span><strong>{value.toString().padStart(2,'0')}</strong><small>{label}</small></div>}
function AlertTable({alerts}:{alerts:Alert[]}){return <section className="card"><div className="cardHead"><div><small>LIVE INTELLIGENCE</small><h2>Recent vulnerability matches</h2></div><button><RefreshCw size={15}/> REFRESH</button></div>{alerts.length===0?<div className="empty"><Shield size={38}/><b>No matched alerts yet</b><p>Add software to your watchlist, then run NVD ingestion.</p></div>:<div className="alerts">{alerts.map(a=><a href={a.vulnerability.sourceUrl} target="_blank" key={a.id}><span className={'severity '+a.vulnerability.severity.toLowerCase()}>{a.vulnerability.severity}</span><div><b>{a.vulnerability.cveId}</b><p>{a.vulnerability.description}</p><small>{a.watchItem.vendor} / {a.watchItem.product}</small></div><strong>{a.vulnerability.cvssScore?.toFixed(1)||'—'}</strong><ChevronRight/></a>)}</div>}</section>}
